### ISSUE TITLE
Deploying sysmon in production

### ISSUE THREAD

**Issue by coleJ98** [0xAnalyst/Sysmon#1]
Hi,

I wanted to ask the approach to deploy this in production. Do you think its a good idea to use startup scripts (as you have used here) in production to deliver the sysmon application and config file to endpoints?

or is using scheduled tasks better? Please let me know your thoughts. I found this blog post regarding sysmon deployment in production where they mention using scheduled task:
https://www.syspanda.com/index.php/2017/02/28/deploying-sysmon-through-gpo/

Thanks in advance! And this is great work

**Comment by 0xAnalyst** [comment]
Thank You, I use GPO startup script but if you don't want to wait until the next restart for your servers the second approach they mentioned in the article should be fine.

**Comment by coleJ98** [comment]
Thanks for the quick reply! Yes I am trying to see which method is more appropriate. Can I also ask how you are deploying this? i,e using a netwok share?

I am having trouble to find a way to also confirm wheter I am receving logs from all the workstations. If you have thoughs on this then please let me know. Thanks again

**Comment by 0xAnalyst** [comment]
I am using a GPO startup script that runs a bat file that pulls the rest of the files from a network share. you can use SCCM and other methods.you test and see which one works for your environment. check Windows Event forwarding setup you have. there is plenty of write-ups on how to configure WEF

**Comment by coleJ98** [comment]
Hi, Yes I have read those guides and in process of implementation! However, the issue that I am really concerned about is the network traffic to the collector server.

Because we do not have a spare collector server, do you know if there are any implications of using the domain controller as a collector server?

For example, will there be any performance issues or any chances of the domain controller receiving too much network traffic?

Your help is much appreciated!

**Comment by 0xAnalyst** [comment]
I don't recommend doing that. I think a spare vm or a workstation could be used to collect the logs. I can check the network traffic this generates in my environment and give you a feedback

**Comment by coleJ98** [comment]
Thanks let me know please! I am looking to deploy this over ~1000 endpoints

**Comment by coleJ98** [comment]
Hi, Did you get a chance to look into this? please let me know regarding network bandwidth resulting from Windows Event Forwarding. It would be ideal not to use the Domain Controller as a collector sever.

Thanks again, much appreciated

**Comment by 0xAnalyst** [comment]
Sorry for the late update, I couldn't get proper bandwidth network utilization for sysmon. In my environment It didn't cause performance issues on the network enabling module load did cause issues though on the machines themselves
